## Use the official Python image from the Docker Hub 
FROM python:3.10.6

# Set the working directory
WORKDIR /app


## Copy the currect directory content into the container at  /app
COPY . .


## Install any needed packages specified in requirements.txt

RUN pip install -r requirements


## MAke port 8000 available to the world outside this container
EXPOSE 8000


## Run app.py when the container launches 
CMD ["python","app.py"]

